name: Run Data Center Scraper

on:
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          cd scraper
          pip install -r requirements.txt
      
      - name: Run scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: |
          cd scraper
          python main.py
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Scraper failed! Check the logs."
          # Add notification logic (Slack, email, etc.)

